# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f60769045e71f339ff688682aa51813c060a19f1c439d1ae782e13cb2d8d6f35fdf6093c83b5b6d50879378b9a3b4a736cdbb5a34fef33f2dae54ec15500a9

test:
  secret_key_base: d401985ccf9546f88dde1e2675c84bb68e7c3efa8986b4d0b3fad1a7068348e40d46145df729e1c0e8c3ce115161c8948c7f44d20b6f6574d23c27d65f31c0a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
